{
  "message": "OK",
  "count": 48,
  "brokers": [
    {
      "id": 11604,
      "company_id": 1514,
      "first_name": "Shlomi",
      "last_name": "Bagdadi",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "7184376100",
      "email": "sb@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "CEO",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "https://www.linkedin.com/in/shlomi-bagdadi/",
      "instagram_url": "",
      "biography": "Shlomi Bagdadi has proven his expertise in Brooklyn’s commercial real estate with his creative eye and a keen understanding of the market.Mr. Bagdadi’s journey begins in Rishon Lezion, Israel where he studied Marketing and Business Management, earning a Bachelor of Arts degree. As a student, he worked for Bank Hapoalim where he accumulated marketing and banking experience as one of the bank’s representatives, working to sign up clients for the bank’s multitude of services. \r\n\r\nFrom there he moved to join Bank Leumi’s headquarters in Tel Aviv, before finally landing in a wholesale company in New York City, thus joining the e-commerce workforce.\r\n\r\nAll the while, Mr. Bagdadi managed a successful online sales business with his family and used the proceeds to invest in commercial real estate properties. The insight he gained on ownership and tenancy needs sparked his passion for real estate.\r\n\r\nMr. Bagdadi has almost two  decades worth of experience in Commercial Real Estate and established Tri State Commercial® Realty in 2014. With a team of skilled brokers and Mr. Bagdadi at the helm, the firm has consecutively received seven “CoStar Power Broker Top Firm Award ” for Four years in a row and also holds first place for closing the most deals in Brooklyn for three years consecutively , according to The Real Deal’s Brooklyn Retail Leasing charts. Mr. Bagdadi has also been nominated for Brownstoner’s RADD Award as one of Brooklyn’s top 50 industry leaders in commercial real estate, development, and architecture.",
      "education": "",
      "specialties": [],
      "memberships_and_associations": "Shlomi Bagdadi is also a member of the a REBNY Brooklyn commercial board and Brooklyn Retail report committee.",
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/011/604/full/Shlomi-Bagdadi-2021.jpg?1644431513",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 11605,
      "company_id": 1514,
      "first_name": "Avi",
      "last_name": "Akiva",
      "phone_number": "7184376100",
      "phone_extension": "110",
      "cell_phone": "7187956396",
      "fax": "7184376100",
      "email": "Avi.A@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Vice President",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/011/605/full/Avi-Akiva.jpg?1644431483",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115650,
      "company_id": 1514,
      "first_name": "Steve",
      "last_name": "Jeffries",
      "phone_number": "2153009688",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "steve.j@tristatecr.com",
      "licenses": [],
      "company_office_id": 9310,
      "address": "1425 Walnut St.",
      "address2": "Suite 300",
      "city": "Philadelphia",
      "state": "PA",
      "zip": "19120",
      "job_title": "Vice President",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/650/full/Steve-Jeffries.jpg?1644341302",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115662,
      "company_id": 1514,
      "first_name": "Chandler",
      "last_name": "Slate",
      "phone_number": "7184376100",
      "phone_extension": "108",
      "cell_phone": "",
      "fax": "",
      "email": "ChandlerS@TriStateCR.com",
      "licenses": [],
      "company_office_id": 12194,
      "address": "1133 Broadway",
      "address2": "Suite 923",
      "city": "New York",
      "state": "NY",
      "zip": "10010",
      "job_title": "VP of Leasing",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/662/full/Chandler-Slate.jpg?1644344283",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115664,
      "company_id": 1514,
      "first_name": "Dov",
      "last_name": "Bleich",
      "phone_number": "7184376100",
      "phone_extension": "111",
      "cell_phone": "",
      "fax": "",
      "email": "Dov.B@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "VP of Leasing",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/664/full/Dov-Bleich-01.jpg?1644342363",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115665,
      "company_id": 1514,
      "first_name": "Eddie",
      "last_name": "Keda",
      "phone_number": "7184376100",
      "phone_extension": "117",
      "cell_phone": "",
      "fax": "",
      "email": "Eddie.K@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Managing Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/665/full/Eddie-Keda.jpg?1644343709",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115666,
      "company_id": 1514,
      "first_name": "Moshe",
      "last_name": "Akiva",
      "phone_number": "7184376100",
      "phone_extension": "116",
      "cell_phone": "",
      "fax": "",
      "email": "Moshe.A@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Managing Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/666/full/Moshe-Akiva-1.jpg?1644341577",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 115667,
      "company_id": 1514,
      "first_name": "Fredy",
      "last_name": "Halabi",
      "phone_number": "7184376100",
      "phone_extension": "114",
      "cell_phone": "",
      "fax": "",
      "email": "Fredy.H@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Managing Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/667/full/Fredy-Halabi---main-pic-web.jpg?1644343393",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115669,
      "company_id": 1514,
      "first_name": "Moses",
      "last_name": "Walter",
      "phone_number": "7184376100",
      "phone_extension": "109",
      "cell_phone": "",
      "fax": "",
      "email": "Moses.W@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/669/full/Moses-Walter-2018a.jpg?1644349652",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115670,
      "company_id": 1514,
      "first_name": "Kirill",
      "last_name": "Galperin",
      "phone_number": "7184376100",
      "phone_extension": "122",
      "cell_phone": "",
      "fax": "",
      "email": "Kirill.G@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/670/full/Kirill-Galperin.jpg?1644342976",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 115671,
      "company_id": 1514,
      "first_name": "Zack",
      "last_name": "Setton",
      "phone_number": "7184376100",
      "phone_extension": "113",
      "cell_phone": "",
      "fax": "",
      "email": "Zack.S@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Senior Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/671/full/Zack-Setton.jpg?1644344211",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115672,
      "company_id": 1514,
      "first_name": "Fred",
      "last_name": "Betesh",
      "phone_number": "7184376100",
      "phone_extension": "115",
      "cell_phone": "",
      "fax": "",
      "email": "fred.b@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Senior Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/672/full/Fred-Betesh-1.jpg?1644342080",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115673,
      "company_id": 1514,
      "first_name": "Robert",
      "last_name": "Mitchell",
      "phone_number": "7184376100",
      "phone_extension": "102",
      "cell_phone": "",
      "fax": "",
      "email": "Robert.M@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Senior Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/673/full/Robert-Mitchell-01.jpg?1644343955",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115674,
      "company_id": 1514,
      "first_name": "Richard",
      "last_name": "Babeck",
      "phone_number": "7184376100",
      "phone_extension": "119",
      "cell_phone": "",
      "fax": "",
      "email": "Richard.B@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Managing Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/674/full/Richard-Babeck.jpg?1644341782",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115677,
      "company_id": 1514,
      "first_name": "Joey",
      "last_name": "Bouzaglou",
      "phone_number": "7184376100",
      "phone_extension": "103",
      "cell_phone": "",
      "fax": "",
      "email": "joseph.b@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Senior Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/677/full/Joey-Bouzaglou.jpg?1644342494",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115679,
      "company_id": 1514,
      "first_name": "Duvy",
      "last_name": "Biller",
      "phone_number": "7184376100",
      "phone_extension": "142",
      "cell_phone": "",
      "fax": "",
      "email": "Duvy.B@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Senior Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/679/full/duvy-biller-600x600-1-480x480.jpg?1644342261",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115680,
      "company_id": 1514,
      "first_name": "Ely",
      "last_name": "Akiva",
      "phone_number": "7184376100",
      "phone_extension": "152",
      "cell_phone": "",
      "fax": "",
      "email": "Ely.A@TriStateCR.com",
      "licenses": [],
      "company_office_id": 12194,
      "address": "1133 Broadway",
      "address2": "Suite 923",
      "city": "New York",
      "state": "NY",
      "zip": "10010",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/680/full/ely-akiva-600x600-1-480x480.jpg?1644341723",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115681,
      "company_id": 1514,
      "first_name": "Isaac",
      "last_name": "Abed",
      "phone_number": "7184376100",
      "phone_extension": "153",
      "cell_phone": "",
      "fax": "",
      "email": "Isaac.A@TriStateCR.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/681/full/isaac-abed-600x600-1-480x480.jpg?1644341470",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115687,
      "company_id": 1514,
      "first_name": "Shaun",
      "last_name": "Lyons",
      "phone_number": "2153009688",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "shaun.l@tristatecr.com",
      "licenses": [],
      "company_office_id": 9310,
      "address": "1425 Walnut St.",
      "address2": "Suite 300",
      "city": "Philadelphia",
      "state": "PA",
      "zip": "19120",
      "job_title": "Principal",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/687/full/Shaun-Lyons-03.jpg?1644343895",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115688,
      "company_id": 1514,
      "first_name": "Kevin",
      "last_name": "Healey",
      "phone_number": "2153009688",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "kevin.h@tristatecr.com",
      "licenses": [],
      "company_office_id": 9310,
      "address": "1425 Walnut St.",
      "address2": "Suite 300",
      "city": "Philadelphia",
      "state": "PA",
      "zip": "19120",
      "job_title": "Managing Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/688/full/Kevin-T-Healey.jpg?1644343604",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115690,
      "company_id": 1514,
      "first_name": "Conor",
      "last_name": "Tunno",
      "phone_number": "2153009688",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "conor.t@tristatecr.com",
      "licenses": [
        {
          "number": "RS340230",
          "state": "PA",
          "expiration": "2022-05-31"
        }
      ],
      "company_office_id": 9310,
      "address": "1425 Walnut St.",
      "address2": "Suite 300",
      "city": "Philadelphia",
      "state": "PA",
      "zip": "19120",
      "job_title": "Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/690/full/Conor_Tunno.jpg?1644344453",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 115692,
      "company_id": 1514,
      "first_name": "Jake",
      "last_name": "Doyle",
      "phone_number": "2153009688",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "jake.d@tristatecr.com",
      "licenses": [],
      "company_office_id": 9310,
      "address": "1425 Walnut St.",
      "address2": "Suite 300",
      "city": "Philadelphia",
      "state": "PA",
      "zip": "19120",
      "job_title": "Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/115/692/full/Jake-Doyle-01.jpg?1644342915",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 120286,
      "company_id": 1514,
      "first_name": "Jack",
      "last_name": "Sardar",
      "phone_number": "7184376100",
      "phone_extension": "106",
      "cell_phone": "",
      "fax": "",
      "email": "jack.s@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "VP Sales",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/120/286/full/jack_sardar_600x600.jpg?1690825160",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 121247,
      "company_id": 1514,
      "first_name": "Nick",
      "last_name": "Anderson",
      "phone_number": "7184376100",
      "phone_extension": "202",
      "cell_phone": "",
      "fax": "",
      "email": "nick.a@tristatecr.com",
      "licenses": [],
      "company_office_id": 12194,
      "address": "1133 Broadway",
      "address2": "Suite 923",
      "city": "New York",
      "state": "NY",
      "zip": "10010",
      "job_title": "Agent",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/121/247/full/nick_anderson_600x600.jpg?1690825582",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 121958,
      "company_id": 1514,
      "first_name": "Daniel",
      "last_name": "Sharabi",
      "phone_number": "7184376100",
      "phone_extension": "158",
      "cell_phone": "",
      "fax": "",
      "email": "daniel.s@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "/images/broker_default_photos/photo-missing-full.png",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 123816,
      "company_id": 1514,
      "first_name": "Joseph",
      "last_name": "Cohen",
      "phone_number": "7184376100",
      "phone_extension": "163",
      "cell_phone": "9175385271",
      "fax": "",
      "email": "joseph.c@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/123/816/full/TSCR-map-peg---2021-HD.jpg?1688143694",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 124542,
      "company_id": 1514,
      "first_name": "Avrum",
      "last_name": "Deutsch",
      "phone_number": "7184376100",
      "phone_extension": "164",
      "cell_phone": "",
      "fax": "",
      "email": "avrum.d@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/124/542/full/TSCR-map-peg---2019.jpg?1657635106",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 124943,
      "company_id": 1514,
      "first_name": "Victoria",
      "last_name": "Amador",
      "phone_number": "7184376100",
      "phone_extension": "160",
      "cell_phone": "9173413937",
      "fax": "",
      "email": "victoria.a@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/124/943/full/victoria_amador_600x600.jpg?1690825548",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 131946,
      "company_id": 1514,
      "first_name": "Hindy",
      "last_name": "German",
      "phone_number": "7184376100",
      "phone_extension": "203",
      "cell_phone": "7182083021",
      "fax": "",
      "email": "hindy.g@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Senior Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/131/946/full/TSCR-map-peg---2019square.jpg?1664404404",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 137264,
      "company_id": 1514,
      "first_name": "Victor",
      "last_name": "Safenia",
      "phone_number": "7184376100",
      "phone_extension": "165",
      "cell_phone": "",
      "fax": "",
      "email": "victor.sf@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/137/264/full/TSCR-map-peg---2021-HD.jpg?1671636218",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 137752,
      "company_id": 1514,
      "first_name": "Joey",
      "last_name": "Sakkal",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "joey.s@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/137/752/full/Joey_Sakkal_600x600.jpg?1690825780",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 138312,
      "company_id": 1514,
      "first_name": "Leo",
      "last_name": "Beda",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "Leo.B@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/138/312/full/TSCR-map-peg---2019square.jpg?1690825665",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 140133,
      "company_id": 1514,
      "first_name": "Maurice",
      "last_name": "Amar",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "maurice.a@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/140/133/full/Maurice_Amar_600x600.jpg?1690825565",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 142950,
      "company_id": 1514,
      "first_name": "Harry",
      "last_name": "Bouzaglou",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "harry.b@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/142/950/full/TSC-Logo2022-header.jpg?1681491951",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 143700,
      "company_id": 1514,
      "first_name": "Michael",
      "last_name": "Bauer",
      "phone_number": "9176583926",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "michael.b@tristatecr.com",
      "licenses": [],
      "company_office_id": 12194,
      "address": "1133 Broadway",
      "address2": "Suite 923",
      "city": "New York",
      "state": "NY",
      "zip": "10010",
      "job_title": "Admin",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "/images/broker_default_photos/photo-missing-full.png",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 143739,
      "company_id": 1514,
      "first_name": "Samuel",
      "last_name": "Shouela",
      "phone_number": "7184376100",
      "phone_extension": "212",
      "cell_phone": "",
      "fax": "",
      "email": "samuel.s@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/143/739/full/TSCR-map-peg---2019.jpg?1682699192",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 145103,
      "company_id": 1514,
      "first_name": "Jacob",
      "last_name": "Twena",
      "phone_number": "7184376100",
      "phone_extension": "920",
      "cell_phone": "",
      "fax": "",
      "email": "jacob.t@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Senior Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/145/103/full/TSCR-map-peg---2021-HD.jpg?1684167905",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 149543,
      "company_id": 1514,
      "first_name": "Michael",
      "last_name": "Elkharrat",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "michael.e@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/149/543/full/TSCR-map-peg---2021-HD.jpg?1689786983",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": false,
      "force_include_on_broker_plugin": true
    },
    {
      "id": 152446,
      "company_id": 1514,
      "first_name": "Mendel",
      "last_name": "Jacobson",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "mendel.j@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Director",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/152/446/full/TSCR-map-peg---2019square.jpg?1691673649",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 157349,
      "company_id": 1514,
      "first_name": "Hillel",
      "last_name": "Schoenfeld",
      "phone_number": "7184376100",
      "phone_extension": "206",
      "cell_phone": "",
      "fax": "",
      "email": "hillel.s@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/157/349/full/TSC-logo-Vertical-2023a.jpg?1694445032",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 157351,
      "company_id": 1514,
      "first_name": "Sammy",
      "last_name": "Levy",
      "phone_number": "7184376100",
      "phone_extension": "215",
      "cell_phone": "",
      "fax": "",
      "email": "sammy.l@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/157/351/full/TSC-logo-Vertical-2023a.jpg?1694445413",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 158691,
      "company_id": 1514,
      "first_name": "John",
      "last_name": "McClatchy",
      "phone_number": "7184376100",
      "phone_extension": "218",
      "cell_phone": "",
      "fax": "",
      "email": "john.mc@tristatecr.com",
      "licenses": [],
      "company_office_id": 9310,
      "address": "1425 Walnut St.",
      "address2": "Suite 300",
      "city": "Philadelphia",
      "state": "PA",
      "zip": "19120",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/158/691/full/TSCR-map-peg---2019square.jpg?1695066356",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 159845,
      "company_id": 1514,
      "first_name": "Mendel",
      "last_name": "Sears",
      "phone_number": "7184376100",
      "phone_extension": "204",
      "cell_phone": "8453673370",
      "fax": "",
      "email": "mendel.s@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/159/845/full/TSCR-map-peg---2019square.jpg?1695747502",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 168361,
      "company_id": 1514,
      "first_name": "Sherry",
      "last_name": "Chera",
      "phone_number": "7184376100",
      "phone_extension": "105",
      "cell_phone": "",
      "fax": "",
      "email": "sherry.c@tristatecr.com",
      "licenses": [],
      "company_office_id": 12194,
      "address": "1133 Broadway",
      "address2": "Suite 923",
      "city": "New York",
      "state": "NY",
      "zip": "10010",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/168/361/full/TSCR-map-peg---2021-HD.jpg?1699907167",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 173040,
      "company_id": 1514,
      "first_name": "Freddy",
      "last_name": "Bagdadi",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "freddy.b@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/173/040/full/TSCR-map-peg---2019.jpg?1702484667",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 177828,
      "company_id": 1514,
      "first_name": "William",
      "last_name": "Ciccarelli",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "william.c@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "/images/broker_default_photos/photo-missing-full.png",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 181684,
      "company_id": 1514,
      "first_name": "Morris",
      "last_name": "Mishan",
      "phone_number": "7184376100",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "morris.m@tristatecr.com",
      "licenses": [],
      "company_office_id": 1850,
      "address": "148 39th st",
      "address2": "Suite A07",
      "city": "Brooklyn",
      "state": "NY",
      "zip": "11232",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/181/684/full/TSCR-map-peg---2019---left-shadow.jpg?1706811522",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    },
    {
      "id": 187677,
      "company_id": 1514,
      "first_name": "Remy",
      "last_name": "Zohni",
      "phone_number": "2153009688",
      "phone_extension": "",
      "cell_phone": "",
      "fax": "",
      "email": "remy.z@tristatecr.com",
      "licenses": [],
      "company_office_id": 9310,
      "address": "1425 Walnut St.",
      "address2": "Suite 300",
      "city": "Philadelphia",
      "state": "PA",
      "zip": "19120",
      "job_title": "Associate",
      "facebook_url": "",
      "twitter_url": "",
      "linked_in_url": "",
      "instagram_url": "",
      "biography": null,
      "education": null,
      "specialties": [],
      "memberships_and_associations": null,
      "profile_photo_url": "https://s3.amazonaws.com/buildout-production/users/profile_photos/000/187/677/full/TSCR-map-peg---2021-HD.jpg?1709920621",
      "bio_pdf_url": null,
      "can_have_properties": true,
      "external_id": null,
      "managing_director": false,
      "custom_fields": {

      },
      "hide_on_broker_plugin": true,
      "force_include_on_broker_plugin": false
    }
  ]
}