import '../app.css';
import Multiselect from '../Components/multiselect';

export function Neighborhoods (props) {
  const selectlabel = "Neighborhoods";
  const NeighborhoodsOptions = [
    'All',
    'Allerton',
    'Astoria',
    'Bala Cynwyd ',
    'Bath Beach',
    'Bay Ridge',
    'Bed-Stuy',
    'Bella Vista ',
    'Belmont',
    'Bensonhurst',
    'Boerum Hill',
    'Borough Park',
    'Borough of West Chester ',
    'Brewerytown',
    'Briarwood',
    'Brighton Beach',
    'Brooklyn Heights',
    'Brownsville',
    'Bushwick',
    'Callowhill',
    'Canarsie',
    'Carrol Gardens',
    'Cental Business District',
    'Center City',
    'Central Business District ',
    'Chelsea',
    'Chestnut Hill',
    'City Avenue District ',
    'Clinton Hill',
    'Cobble Hill',
    'Concourse',
    'Coney Island',
    'Corona',
    'Crown Heights',
    'Cypress Hills',
    'Downtown Brooklyn',
    'East Flatbush',
    'East Harlem',
    'East Kensington',
    'East New York',
    'East Rockhill Township',
    'East Village',
    'East Williamsburg',
    'Elmhurst',
    'Elverson',
    'Fairmount',
    'Fishtown',
    'Fishtown ',
    'Flatbush',
    'Flatlands',
    'Fordham',
    'Fort George',
    'Frankford',
    'Garment District',
    'Germantown ',
    'Graduate Hospital ',
    'Gramercy',
    'Gravesend',
    'Grays Ferry',
    'Greenpoint',
    'Greenwood',
    'Harlem',
    'Howard Beach',
    'Hunter\'s Point',
    'Hunting Park/ N Philly',
    'Jackson Heights',
    'Jamaica',
    'Jerome Park',
    'Jersey City',
    'Kensington',
    'Kew Gardens',
    'Kips Bay',
    'Lederach ',
    'Lenox Hill',
    'Lincoln Square',
    'Logan Square',
    'Logan Square ',
    'Logan Township',
    'Long Island',
    'Long Island City',
    'Longwood',
    'Lower East Side',
    'Lower Merion Township',
    'Malvern ',
    'Manayunk',
    'Manhattan Valley',
    'Maple Shade ',
    'Marine Park',
    'Market East',
    'Marus Hook ',
    'Melrose',
    'Middle Village',
    'Midtown',
    'Midtown Village ',
    'Midtown Villiage ',
    'Midwood',
    'Montgomeryville ',
    'Morrisania',
    'Mott Haven',
    'Mt Airy',
    'Mt. Airy',
    'Mt. Eden',
    'Mt. Hope',
    'Murray Hill',
    'New Jersey',
    'Nomad',
    'Norris Square',
    'North Broad Street/ Temple University Hospital ',
    'Northeast Philadelphia ',
    'Northern Liberties',
    'Norwood',
    'Nothern Liberties ',
    'Ocean Parkway',
    'Old City',
    'Overbrook',
    'Ozone Park',
    'Paoli',
    'Paoli ',
    'Park Slope',
    'Phoenixville ',
    'Phoenixville Borough ',
    'Prospect Heights',
    'Prospect Lefferts Garden',
    'Queen Village',
    'Red Hook',
    'Richmond Hill',
    'Ridgewood',
    'Rittenhouse Square',
    'Rittenhouse Square ',
    'Rockaway Park',
    'Sheepshead Bay',
    'SoHo',
    'South Bronx',
    'South Philadelpha ',
    'South Philadelphia ',
    'South Phillly ',
    'South Philly',
    'South Slope',
    'Staten Island',
    'Sugar Hill',
    'Sunset Park',
    'Torresdale ',
    'Union City',
    'Union Square',
    'University City',
    'Upper East Side',
    'Upper West Side',
    'Villanova ',
    'Wakefield',
    'Warminster',
    'Washingsont Square ',
    'West Bronx',
    'West Chester',
    'West Chester Borough',
    'West Farms',
    'West Philadelphia ',
    'West Philly',
    'West Village',
    'Westtown Township ',
    'Whitman',
    'Williamsburg',
    'Yorkville'
]
.map(option => ({ value: option.toLowerCase(), label: option }));


  return (
    <div className=''>
      <Multiselect colourOptions={NeighborhoodsOptions} selectlabel={selectlabel}/>
    </div>
  );
}
